// src/mockData.js

// Data for "Popular Products"
export const popularProducts = [
  {
    id: 1,
    tag: 'Hot',
    category: 'Snack',
    title: 'Fresh organic villa farm lemon',
    rating: 4.0,
    author: 'NestFood',
    price: 28.85,
    oldPrice: 32.8,
    img: '/images/product-1.png',
  },
  {
    id: 2,
    tag: 'Sale',
    category: 'Hodo Foods',
    title: 'Best snakes with hazel nut pack',
    rating: 3.5,
    author: 'Stouffer',
    price: 52.85,
    oldPrice: 55.8,
    img: '/images/product-2.png',
  },
  {
    id: 3,
    tag: 'New',
    category: 'Snack',
    title: 'Organic fresh vanilla farm watermelon',
    rating: 4.0,
    author: 'Starkist',
    price: 48.85,
    oldPrice: 52.8,
    img: '/images/product-3.png',
  },
  {
    id: 4,
    category: 'Vegetables',
    title: 'Fresh organic apple 1kg simla marning',
    rating: 4.0,
    author: 'NestFood',
    price: 17.85,
    oldPrice: 19.8,
    img: '/images/product-4.png',
  },
  {
    id: 5,
    tag: '-14%',
    category: 'Pet Foods',
    title: 'Blue Diamond Almonds Lightly Salted',
    rating: 4.0,
    author: 'NestFood',
    price: 23.85,
    oldPrice: 25.8,
    img: '/images/product-5.png',
  },
  {
    id: 6,
    category: 'Hodo Foods',
    title: 'Chobani Complete Vanilla Greek Yogurt',
    rating: 4.0,
    author: 'NestFood',
    price: 54.85,
    oldPrice: 55.8,
    img: '/images/product-6.png',
  },
  {
    id: 7,
    category: 'Meats',
    title: 'Canada Dry Ginger Ale - 2 L Bottle',
    rating: 4.0,
    author: 'NestFood',
    price: 32.85,
    oldPrice: 33.8,
    img: '/images/product-7.png',
  },
  {
    id: 8,
    tag: 'Sale',
    category: 'Snack',
    title: 'Encore Seafoods Stuffed Alaskan Salmon',
    rating: 4.0,
    author: 'NestFood',
    price: 35.85,
    oldPrice: 37.8,
    img: '/images/product-8.png',
  },
  {
    id: 9,
    tag: 'Hot',
    category: 'Coffes',
    title: "Gorton's Beer Battered Fish Fillets",
    rating: 4.0,
    author: 'Old El Paso',
    price: 23.85,
    oldPrice: 25.8,
    img: '/images/product-9.png',
  },
  {
    id: 10,
    category: 'Cream',
    title: 'Haagen-Dazs Caramel Cone Ice Cream',
    rating: 2.0,
    author: 'Tyson',
    price: 22.85,
    oldPrice: 24.8,
    img: '/images/product-10.png',
  },
];

// Data for "Daily Best Sells"
export const dailyBestSells = [
  {
    id: 11,
    tag: 'Save 25%',
    category: 'Hodo Foods',
    title: 'All Natural Italian-Style Chicken Meatballs',
    rating: 4.5,
    price: 238.85,
    oldPrice: 245.8,
    sold: 90,
    total: 120,
    img: '/images/best-1.png',
  },
  {
    id: 12,
    tag: 'Sale',
    category: 'Hodo Foods',
    title: "Angie's Boomchickapop Sweet and Salty",
    rating: 4.0,
    price: 238.85,
    oldPrice: 245.8,
    sold: 70,
    total: 120,
    img: '/images/best-2.png',
  },
  {
    id: 13,
    tag: 'Best sale',
    category: 'Hodo Foods',
    title: 'Foster Farms Takeout Crispy Classic',
    rating: 4.2,
    price: 238.85,
    oldPrice: 245.8,
    sold: 60,
    total: 120,
    img: '/images/best-3.png',
  },
  {
    id: 14,
    tag: 'Save 15%',
    category: 'Hodo Foods',
    title: 'Blue Diamond Almonds Lightly Salted',
    rating: 4.1,
    price: 238.85,
    oldPrice: 245.8,
    sold: 80,
    total: 120,
    img: '/images/best-4.png',
  },
];

// Data for "Deals of the Day"
export const dealsOfTheDay = [
  {
    id: 15,
    title: 'Seeds of Change Organic Quinoa, Brown, & Red Rice',
    rating: 4.0,
    author: 'NestFood',
    price: 32.85,
    oldPrice: 33.8,
    img: '/images/deal-1.png',
  },
  {
    id: 16,
    title: 'Perdue Simply Smart Organics Gluten Free',
    rating: 4.0,
    author: 'Old El Paso',
    price: 24.85,
    oldPrice: 26.8,
    img: '/images/deal-2.png',
  },
  {
    id: 17,
    title: 'Signature Wood-Fired Mushroom and Caramelized',
    rating: 3.0,
    author: 'Progresso',
    price: 12.85,
    oldPrice: 13.8,
    img: '/images/deal-3.png',
  },
  {
    id: 18,
    title: 'Simply Lemonade with Raspberry Juice',
    rating: 3.0,
    author: 'Yoplait',
    price: 15.85,
    oldPrice: 16.8,
    img: '/images/deal-4.png',
  },
];

// Data for "Top" columns
export const topSelling = [
  {
    id: 19,
    title: 'Nestle Original Coffee-Mate Coffee Creamer',
    rating: 4.0,
    price: 32.85,
    oldPrice: 33.8,
    img: '/images/top-1.png',
  },
  {
    id: 20,
    title: 'Nestle Original Coffee-Mate Coffee Creamer',
    rating: 4.0,
    price: 32.85,
    oldPrice: 33.8,
    img: '/images/top-2.png',
  },
  {
    id: 21,
    title: 'Nestle Original Coffee-Mate Coffee Creamer',
    rating: 4.0,
    price: 32.85,
    oldPrice: 33.8,
    img: '/images/top-3.png',
  },
];
// (Create similar arrays for trendingProducts, recentlyAdded, topRated)
